<a href="https://colab.research.google.com/github/yawpAI/colab/blob/main/boston.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [166]:
from sklearn.datasets import load_boston 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
 


In [167]:
bunch = load_boston()
print(bunch.data.shape)
print(bunch.target.shape)

(506, 13)
(506,)


In [168]:
bunch.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [169]:
bunch.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [170]:
print(bunch.feature_names)
print(bunch.DESCR)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial hig

In [171]:
X_train, X_test, y_train, y_test = train_test_split(bunch.data, bunch.target, test_size=0.20)

In [172]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [173]:
val_size = int(len(X_train) * 0.2)
print(val_size)

80


In [174]:
X_val_scaled = X_train_scaled[-val_size:]
y_val = y_train[-val_size:]
X_train_scaled = X_train_scaled[:-val_size]
y_train = y_train[:-val_size]

In [175]:
modelTF = tf.keras.models.Sequential()
modelTF.add(tf.keras.layers.Dense(1, input_shape=(X_train_scaled.shape[1],)))

In [176]:
modelTF.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9), loss='mse')

In [177]:
def scheduler(epoch, lr):
  if epoch < 10:
    return lr
  else:
    return lr * tf.math.exp(-0.1)

In [178]:
modelTF.fit(X_train_scaled, y_train, validation_data=(X_val_scaled, y_val), epochs = 100, callbacks=[tf.keras.callbacks.LearningRateScheduler(scheduler)])

Epoch 1/100
11/11 [==============================] - 0s 16ms/step - loss: 446.9304 - val_loss: 74.1747
Epoch 2/100
11/11 [==============================] - 0s 5ms/step - loss: 49.6580 - val_loss: 91.7186
Epoch 3/100
11/11 [==============================] - 0s 5ms/step - loss: 78.9404 - val_loss: 56.2473
Epoch 4/100
11/11 [==============================] - 0s 5ms/step - loss: 35.4567 - val_loss: 46.6000
Epoch 5/100
11/11 [==============================] - 0s 5ms/step - loss: 25.2512 - val_loss: 35.7031
Epoch 6/100
11/11 [==============================] - 0s 5ms/step - loss: 23.5356 - val_loss: 34.6137
Epoch 7/100
11/11 [==============================] - 0s 5ms/step - loss: 22.9435 - val_loss: 36.1983
Epoch 8/100
11/11 [==============================] - 0s 6ms/step - loss: 21.8844 - val_loss: 36.8539
Epoch 9/100
11/11 [==============================] - 0s 5ms/step - loss: 21.5521 - val_loss: 34.9636
Epoch 10/100
11/11 [==============================] - 0s 6ms/step - loss: 21.4147 - val_l

In [179]:
modelTF.evaluate(X_train_scaled, y_train)

11/11 [==============================] - 0s 1ms/step - loss: 19.3087


19.30872344970703

In [180]:
import numpy as np
def R_squared(y, y_pred):
  SSE = np.linalg.norm(y - y_pred)
  print('SSE = ' + str(SSE))
  SST = np.linalg.norm(y-y.mean())
  print('SST = ' + str(SST))
  return 1.0 - (SSE/SST)**2

In [181]:
y_test.mean()

21.75882352941176

In [182]:
np.mean(y_test)

21.75882352941176

In [183]:
R_squared(y_test, modelTF.predict(X_test_scaled)[:,0])  ### This 1 layer NN is OK, but is improved with a 2nd Dense layer below.

SSE = 49.87340338841857
SST = 95.89946328746335


0.7295383717634569

In [184]:
from sklearn.neural_network import MLPRegressor

model = MLPRegressor()
model.fit(X_train_scaled, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100,), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=200,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [185]:
model.score(X_test_scaled, y_test)

0.6836153064640043

In [186]:
modelTF2 = tf.keras.models.Sequential()
modelTF2.add(tf.keras.layers.Dense(100, activation='relu', input_shape=(X_train_scaled.shape[1],)))
modelTF2.add(tf.keras.layers.Dense(1))

In [187]:
#modelTF2.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.9), loss='mse')
modelTF2.compile(optimizer='adam', loss='mse')

In [188]:
modelTF2.fit(X_train_scaled, y_train, validation_data=(X_val_scaled, y_val), epochs=200)

Epoch 1/200
11/11 [==============================] - 0s 17ms/step - loss: 579.7878 - val_loss: 649.4435
Epoch 2/200
11/11 [==============================] - 0s 5ms/step - loss: 532.1147 - val_loss: 622.0563
Epoch 3/200
11/11 [==============================] - 0s 5ms/step - loss: 492.4397 - val_loss: 594.6123
Epoch 4/200
11/11 [==============================] - 0s 6ms/step - loss: 500.4800 - val_loss: 565.7939
Epoch 5/200
11/11 [==============================] - 0s 6ms/step - loss: 460.3949 - val_loss: 535.2379
Epoch 6/200
11/11 [==============================] - 0s 5ms/step - loss: 419.8882 - val_loss: 503.3878
Epoch 7/200
11/11 [==============================] - 0s 5ms/step - loss: 442.2041 - val_loss: 470.4715
Epoch 8/200
11/11 [==============================] - 0s 6ms/step - loss: 417.2697 - val_loss: 434.6356
Epoch 9/200
11/11 [==============================] - 0s 6ms/step - loss: 368.8199 - val_loss: 397.4814
Epoch 10/200
11/11 [==============================] - 0s 7ms/step - loss

In [189]:
R_squared(y_test, modelTF2.predict(X_test_scaled)[:,0])

SSE = 39.63495091129355
SST = 95.89946328746335


0.829185672252824

In [190]:
modelTF2.evaluate(X_test_scaled, y_test)

4/4 [==============================] - 0s 3ms/step - loss: 15.4013


15.401268005371094

In [191]:
modelTF2.predict(X_test_scaled)[:,0] - y_test

array([-0.66004219, -5.07824326,  4.6084301 , -1.69356041, -0.53403053,
        6.2039566 , -2.04433479,  2.76970177, -1.62211876, -4.31007214,
        2.39326935, 25.57143555, -2.32433434,  0.36902847,  1.4560545 ,
       -3.96095238,  2.13440857,  5.86884155,  2.09644852,  4.2478981 ,
        0.07776489, -1.96951408, -4.80983658, -0.82840328, -2.2303009 ,
        3.05649414, -4.18028488, -3.03334198, -1.49715843, -5.17376404,
       -4.42232189,  0.61026421,  2.76745338, -0.18241882,  2.61664314,
       -2.43779831,  2.67424011,  0.33589773, -0.34828377,  1.73040657,
       -4.80938797,  3.26691284,  4.71783485, -0.04220629,  0.45221481,
        0.30141907, -8.66353989, -4.36748848, -0.51593628, -1.76263809,
        4.75944824,  1.18245468, -1.41357079,  3.07025642,  0.53020153,
        1.37841492,  0.70146103, -0.45263405, -0.60312729,  1.74340057,
        2.18420792, -0.81744423, -6.39103279,  0.38819542,  2.75511742,
        2.45378723,  1.6861145 ,  1.16962395,  3.79194107,  0.14

In [192]:
y_test.shape


(102,)

In [193]:
modelTF2.predict(X_test_scaled)[:,0].shape

(102,)

In [195]:
!pip install tensorflow-addons

     |████████████████████████████████| 706kB 2.9MB/s 


In [199]:
#verification of my home grown R_squared in numpy
import tensorflow_addons as tfa
metric = tfa.metrics.r_square.RSquare()
metric.update_state(y_test, modelTF2.predict(X_test_scaled)[:,0])
result = metric.result()
result.numpy()

0.82918566

In [206]:
# layers[0] is the 100 node Dense layer with Input size (D,) where D = # of features = 13 for the Boston data
# get_weights returns the D*M weight matrix of the later, where D is input dim, M is output dim at index 0, AND the bias vector of dim M at index 1
print(modelTF2.layers[0].get_weights()[0].shape)
modelTF2.layers[0].get_weights()[1].shape

(13, 100)


(100,)

In [205]:
X_train.shape

(404, 13)

In [207]:
# the 2nd Dense layer is D = 100, M = 1
print(modelTF2.layers[1].get_weights()[0].shape)
modelTF2.layers[1].get_weights()[1].shape

(100, 1)


(1,)