<a href="https://colab.research.google.com/github/yawpAI/colab/blob/main/boston.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.datasets import load_boston 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
 


In [5]:
bunch = load_boston()
print(bunch.data.shape)
print(bunch.target.shape)

(506, 13)
(506,)


In [6]:
bunch.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [7]:
bunch.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [8]:
print(bunch.feature_names)
print(bunch.DESCR)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial hig

In [9]:
X_train, X_test, y_train, y_test = train_test_split(bunch.data, bunch.target, test_size=0.20)

In [10]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
val_size = int(len(X_train) * 0.2)
print(val_size)

80


In [12]:
X_val_scaled = X_train_scaled[-val_size:]
y_val = y_train[-val_size:]
X_train_scaled = X_train_scaled[:-val_size]
y_train = y_train[:-val_size]

In [13]:
modelTF = tf.keras.models.Sequential()
modelTF.add(tf.keras.layers.Dense(1, input_shape=(X_train_scaled.shape[1],)))

In [14]:
modelTF.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9), loss='mse')

In [15]:
def scheduler(epoch, lr):
  if epoch < 10:
    return lr
  else:
    return lr * tf.math.exp(-0.1)

In [16]:
modelTF.fit(X_train_scaled, y_train, validation_data=(X_val_scaled, y_val), epochs = 100, callbacks=[tf.keras.callbacks.LearningRateScheduler(scheduler)])

Epoch 1/100
11/11 [==============================] - 1s 24ms/step - loss: 490.2095 - val_loss: 51.7842
Epoch 2/100
11/11 [==============================] - 0s 5ms/step - loss: 46.0198 - val_loss: 73.3475
Epoch 3/100
11/11 [==============================] - 0s 5ms/step - loss: 69.9832 - val_loss: 37.0157
Epoch 4/100
11/11 [==============================] - 0s 6ms/step - loss: 37.5195 - val_loss: 37.2117
Epoch 5/100
11/11 [==============================] - 0s 6ms/step - loss: 31.2027 - val_loss: 38.3668
Epoch 6/100
11/11 [==============================] - 0s 6ms/step - loss: 27.7605 - val_loss: 29.0638
Epoch 7/100
11/11 [==============================] - 0s 6ms/step - loss: 25.8435 - val_loss: 28.1087
Epoch 8/100
11/11 [==============================] - 0s 5ms/step - loss: 24.7398 - val_loss: 28.8411
Epoch 9/100
11/11 [==============================] - 0s 6ms/step - loss: 20.3800 - val_loss: 27.3030
Epoch 10/100
11/11 [==============================] - 0s 6ms/step - loss: 17.5081 - val_l

In [17]:
modelTF.evaluate(X_train_scaled, y_train)

11/11 [==============================] - 0s 1ms/step - loss: 21.8527


21.85273551940918

In [18]:
import numpy as np
def R_squared(y, y_pred):
  SSE = np.linalg.norm(y - y_pred)
  print('SSE = ' + str(SSE))
  SST = np.linalg.norm(y-y.mean())
  print('SST = ' + str(SST))
  return 1.0 - (SSE/SST)**2

In [19]:
y_test.mean()

21.76372549019608

In [20]:
np.mean(y_test)

21.76372549019608

In [21]:
R_squared(y_test, modelTF.predict(X_test_scaled)[:,0])  ### This 1 layer NN is OK, but is improved with a 2nd Dense layer below.

SSE = 45.9553219019564
SST = 80.51593497136903


0.6742323580715477

In [22]:
from sklearn.neural_network import MLPRegressor

model = MLPRegressor()
model.fit(X_train_scaled, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(100,), learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=200,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=False,
             warm_start=False)

In [23]:
model.score(X_test_scaled, y_test)

0.5519917238123763

In [24]:
modelTF2 = tf.keras.models.Sequential()
modelTF2.add(tf.keras.layers.Dense(100, activation='relu', input_shape=(X_train_scaled.shape[1],)))
modelTF2.add(tf.keras.layers.Dense(1))

In [25]:
#modelTF2.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.9), loss='mse')
modelTF2.compile(optimizer='adam', loss='mse')

In [26]:
modelTF2.fit(X_train_scaled, y_train, validation_data=(X_val_scaled, y_val), epochs=200)

Epoch 1/200
11/11 [==============================] - 1s 16ms/step - loss: 629.1236 - val_loss: 634.3283
Epoch 2/200
11/11 [==============================] - 0s 6ms/step - loss: 598.2810 - val_loss: 609.7124
Epoch 3/200
11/11 [==============================] - 0s 5ms/step - loss: 598.2589 - val_loss: 585.5402
Epoch 4/200
11/11 [==============================] - 0s 6ms/step - loss: 549.8399 - val_loss: 561.3939
Epoch 5/200
11/11 [==============================] - 0s 6ms/step - loss: 551.4333 - val_loss: 535.0831
Epoch 6/200
11/11 [==============================] - 0s 7ms/step - loss: 540.1664 - val_loss: 507.8602
Epoch 7/200
11/11 [==============================] - 0s 6ms/step - loss: 524.0804 - val_loss: 479.3109
Epoch 8/200
11/11 [==============================] - 0s 6ms/step - loss: 454.3880 - val_loss: 450.4145
Epoch 9/200
11/11 [==============================] - 0s 6ms/step - loss: 381.5008 - val_loss: 418.6219
Epoch 10/200
11/11 [==============================] - 0s 7ms/step - loss

In [27]:
R_squared(y_test, modelTF2.predict(X_test_scaled).flatten())

SSE = 36.043846258187415
SST = 80.51593497136903


0.7995996035816124

In [28]:
modelTF2.evaluate(X_test_scaled, y_test)

4/4 [==============================] - 0s 2ms/step - loss: 12.7369


12.73685073852539

In [29]:
modelTF2.predict(X_test_scaled)[:,0] - y_test

array([ -1.47560616,  -3.28781471,   1.81520576,   3.14037018,
        -5.53947296,  -1.38736153,   4.17818451,  -5.9695507 ,
         5.02372742,   6.65250874,  -0.93657684,   0.70539474,
         3.56763916,   1.37331123,  -0.30176506,  -1.1961834 ,
         0.3839016 ,   1.10175495,   0.38543625,  -1.51117668,
        -1.40709572,  -3.53442574,  -3.34291649,  -1.6789505 ,
        -1.82613335,  -2.84172363,  -3.97225571,  -0.02308121,
         3.28583031, -22.17400932,  -1.10708771,  -3.51550255,
        -0.72263107,  -3.38381577,  -2.74402695,   1.80235291,
         2.94119492,   0.5085907 ,   2.09241714,   0.89626656,
         3.00906258,   1.08293991,  -0.16901569,  -1.21078606,
        -0.43290329,  -0.26988373,   1.1957737 ,  -1.23248367,
         2.17145805,   2.18128853,   2.39040527,   2.25976219,
         0.952005  ,   5.10431404,  -1.03551025,  -0.42396584,
        -3.80573292,  -0.92402248,   0.02689629,   0.64727097,
         1.17070084,   0.69492836,  -1.55692844,   1.78

In [30]:
y_test.shape


(102,)

In [31]:
modelTF2.predict(X_test_scaled)[:,0].shape

(102,)

In [32]:
!pip install tensorflow-addons

In [33]:
#verification of my home grown R_squared in numpy
import tensorflow_addons as tfa
metric = tfa.metrics.r_square.RSquare()
metric.update_state(y_test, modelTF2.predict(X_test_scaled).flatten())
result = metric.result()
result.numpy()

0.79959965

In [34]:
# layers[0] is the 100 node Dense layer with Input size (D,) where D = # of features = 13 for the Boston data
# get_weights returns the D*M weight matrix of the later, where D is input dim, M is output dim at index 0, AND the bias vector of dim M at index 1
print(modelTF2.layers[0].get_weights()[0].shape)
modelTF2.layers[0].get_weights()[1].shape

(13, 100)


(100,)

In [35]:
X_train.shape

(404, 13)

In [36]:
# the 2nd Dense layer is D = 100, M = 1
print(modelTF2.layers[1].get_weights()[0].shape)
modelTF2.layers[1].get_weights()[1].shape

(100, 1)


(1,)

In [37]:
modelTF2.save('modelTF2.h5')

In [38]:
%ls

modelTF2.h5  sample_data/


In [39]:
model_again = tf.keras.models.load_model('modelTF2.h5')

In [40]:
R_squared(y_test, model_again.predict(X_test_scaled).flatten())

SSE = 36.043846258187415
SST = 80.51593497136903


0.7995996035816124

In [42]:
model_again.layers