<a href="https://colab.research.google.com/github/yawpAI/colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3]

In [ ]:
A = np.array(l)

In [ ]:
for e in l:
  print(e)

1
2
3


In [ ]:
for i in A:
  print(i)

1
2
3


In [ ]:
l.append("d")

In [ ]:
l

[1, 2, 3, 'd']

In [ ]:
A.append("d"). #arrays have fixed length

AttributeError: ignored

In [ ]:
l + [4,5,6]

[1, 2, 3, 'd', 4, 5, 6]

In [ ]:
A + np.array([4]). #broadcasting, adding 4 to all elements in A

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6]). # vector addition since dims are the same

array([5, 7, 9])

In [ ]:
A + np.array([4,5]). #incompatible shapes for broadcasting and cannot add 2 vectors of 2 sizes

ValueError: ignored

In [ ]:
A * 2. # element wise multiplication

array([2, 4, 6])

In [ ]:
l * 2. #repeated concatenation

[1, 2, 3, 'd', 1, 2, 3, 'd']

In [ ]:
l + l. #addition for lists is always concatenation

[1, 2, 3, 'd', 1, 2, 3, 'd']

In [ ]:
l = [1,2,3]. #must iterate to add to list elements
l2 = []
for i in l:
  l2.append(i + 3)
l2

[4, 5, 6]

In [ ]:
#list comprehensions
l2 = [e + 3 for e in l]
l2

[4, 5, 6]

In [ ]:
l**2. #no multiplication for lists, must iterate

TypeError: ignored

In [ ]:
l3 = [e**2 for e in l]
l3

[1, 4, 9]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A). #all functions over the vector

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
np.sin(A)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
A = np.array([1,2])
B = [e**2 for e in A]

In [ ]:
A.dot(B)

9

In [ ]:
dot = 0
for i in range(len(A)):
  dot += A[i] * B[i]
dot

9

In [ ]:
A * B. #element wise

array([1, 8])

In [ ]:
np.sum(A*B)

9

In [ ]:
(A*B).sum()

9

In [ ]:
np.dot(A,B)

9

In [ ]:
# new operator
A @ B

9

In [ ]:
np.norm(A)

AttributeError: ignored

In [ ]:
Amag = np.sqrt(A @ A)
print(Amag)

2.23606797749979


In [ ]:
np.linalg.norm(A). #norm

2.23606797749979

In [ ]:
# cosine
cos = A @ B / (np.linalg.norm(A) * np.linalg.norm(B))
cos

0.9761870601839528

In [ ]:
angle = np.arccos(cos)
angle

0.21866894587394162

In [45]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [46]:
L[0]

[1, 2]

In [47]:
L[0][1]

2

In [49]:
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

In [50]:
A[0][1]

2

In [51]:
A[0,1]

2

In [53]:
A[:,0]

array([1, 3])

In [54]:
A.T

array([[1, 3],
       [2, 4]])

In [55]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [56]:
np.exp(L). #pass in a list and converted to array

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [58]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
A & B. #not for matrices

ValueError: ignored

In [60]:
A.dot(B) #matrix multiplication

array([[ 9, 12, 15],
       [19, 26, 33]])

In [61]:
A * B. # element wise won't work as dims are wrong

ValueError: ignored

In [62]:
A.dot(A.T)

array([[ 5, 11],
       [11, 25]])

In [63]:
np.linalg.det(A)

-2.0000000000000004

In [64]:
np.linalg.inv(A)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [65]:
A.dot(np.linalg.inv(A))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [66]:
np.trace(A)

5

In [67]:
np.diag(A)

array([1, 4])

In [75]:
np.diag([1,4]) #creates a diagonal matrix, overloaded function

array([[1, 0],
       [0, 4]])

In [69]:
np.linalg.eig(A). #eigenvalues followed by eigenvectors

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [70]:
Lam, V = np.linalg.eig(A)

In [72]:
V[:,0] * Lam[0] == A @ V[:,0] #false only due to numerical rounding

array([ True, False])

In [76]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])  #USE THE np.allclose() to show equality within tolerance of round off (numerical precision)

True

In [81]:
np.allclose(V @ np.diag(Lam), A @ V)

True

In [85]:
np.linalg.eigh(np.array([[1,2],[2,1]])) #use on real symmetric or complex Hermitian

(array([-1.,  3.]), array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [5]:
import numpy as np
A = np.array([[1,1],[1.5,4]])

In [8]:
b = np.array([2200,5050])

In [9]:
np.linalg.solve(A,b). # use this, not inv, to solve linear systems

array([1500.,  700.])

In [10]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
10*np.ones([2,3])

array([[10., 10., 10.],
       [10., 10., 10.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.random()

0.5895998414378812

In [16]:
np.random.random([2,3]) #uniform [0.1]

array([[0.8390736 , 0.18670403, 0.02163782],
       [0.36084257, 0.68834323, 0.71402946]])

In [19]:
np.random.randn(2,3)   #not a tuple as shape but dims separately

array([[-0.59295511, -0.42165964,  0.48330711],
       [ 0.05568073, -0.53611651, -0.22119603]])

In [21]:
R = np.random.randn(10000)

In [22]:
R.mean()

0.0012363647466054498

In [23]:
np.mean(R)

0.0012363647466054498

In [24]:
R.var()

0.986898039139008

In [25]:
R.std()

0.9934274201666713

In [26]:
np.sqrt(R.var())

0.9934274201666713

In [30]:
R = np.random.randn(10000,3)
R

array([[-0.43855667,  1.24667769,  0.43436546],
       [-0.16502832,  0.03007189,  0.30369541],
       [-0.17925272, -0.1218918 ,  0.37170532],
       ...,
       [ 0.17194284, -0.47436069, -0.92469024],
       [ 0.81471341,  0.43130153, -0.9211342 ],
       [-0.82272615, -0.73318291, -0.26393134]])

In [28]:
R.mean(axis=0)   #mean of each col

array([ 0.01443273, -0.01411507,  0.00397542])

In [29]:
R.mean(axis=1) #mean of each row

array([-0.35663288, -0.43124011,  0.82614724, ...,  0.25305025,
        0.32292007, -0.32846902])

In [34]:
R.var(axis=0)

array([0.99414444, 1.01092006, 0.99538686])

In [35]:
R.var(axis=1). #each col is N(0,1) so rows are NOT

array([0.4735399 , 0.03695954, 0.06116479, ..., 0.20256767, 0.55436156,
       0.06005185])

In [31]:
np.cov(R) #cov matrix with rows as features - opposite of other libs and what one wants, so use transpose in this particular function

array([[ 0.71030985,  0.08594686,  0.02944251, ..., -0.28010667,
        -0.1771331 ,  0.04291782],
       [ 0.08594686,  0.05543931,  0.06741633, ..., -0.12722211,
        -0.20974915,  0.06796476],
       [ 0.02944251,  0.06741633,  0.09174719, ..., -0.14392546,
        -0.27432174,  0.09077167],
       ...,
       [-0.28010667, -0.12722211, -0.14392546, ...,  0.30385151,
         0.46007169, -0.14699714],
       [-0.1771331 , -0.20974915, -0.27432174, ...,  0.46007169,
         0.83154233, -0.27315786],
       [ 0.04291782,  0.06796476,  0.09077167, ..., -0.14699714,
        -0.27315786,  0.09007778]])

In [33]:
np.cov(R).shape

(10000, 10000)

In [36]:
np.cov(R.T) # the proper COV matrix for 3 col, 10k observations

array([[ 0.99424387, -0.00314512, -0.0100045 ],
       [-0.00314512,  1.01102116,  0.00950371],
       [-0.0100045 ,  0.00950371,  0.99548641]])

In [37]:
np.cov(R, rowvar=False)

array([[ 0.99424387, -0.00314512, -0.0100045 ],
       [-0.00314512,  1.01102116,  0.00950371],
       [-0.0100045 ,  0.00950371,  0.99548641]])

In [38]:
np.random.randint(0, 10, [3,3]). # low, high (exclusive), and shape

array([[0, 9, 2],
       [1, 3, 8],
       [7, 5, 4]])

In [40]:
np.random.choice([1,2,3,4,5], size=[3,3], replace=True, p=[.1, .1, .1, .6, .1]) # choose from first arg, to size, with/without replacement, with given probs (if absent, uniform)

array([[4, 1, 4],
       [1, 4, 1],
       [2, 4, 4]])

In [43]:
np.random.choice(100, size=[10,10], replace=False) # choose from 0 to 99 in uniform distribution without replacement

array([[24, 22, 86, 64, 34, 43, 93, 38, 30, 76],
       [70, 68, 46, 29, 60, 74, 44, 31, 91, 57],
       [26, 72, 16, 39, 59, 15,  2,  4, 33, 45],
       [32, 40, 49, 47, 75, 17, 81, 98, 36,  8],
       [53, 50, 10, 99, 51, 63, 12, 84, 66, 96],
       [67, 14, 89, 97, 21, 48, 37,  5,  9, 42],
       [25,  1, 54, 90, 20, 85, 79, 94, 87, 58],
       [83, 56,  0, 11,  3, 13, 55, 41, 80, 35],
       [69, 62, 19, 18, 27, 92, 65, 71, 82, 88],
       [61,  6, 73,  7, 28, 78, 77, 23, 95, 52]])