<a href="https://colab.research.google.com/github/yawpAI/colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3]

In [ ]:
A = np.array(l)

In [ ]:
for e in l:
  print(e)

1
2
3


In [ ]:
for i in A:
  print(i)

1
2
3


In [ ]:
l.append("d")

In [ ]:
l

[1, 2, 3, 'd']

In [ ]:
A.append("d"). #arrays have fixed length

AttributeError: ignored

In [ ]:
l + [4,5,6]

[1, 2, 3, 'd', 4, 5, 6]

In [ ]:
A + np.array([4]). #broadcasting, adding 4 to all elements in A

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6]). # vector addition since dims are the same

array([5, 7, 9])

In [ ]:
A + np.array([4,5]). #incompatible shapes for broadcasting and cannot add 2 vectors of 2 sizes

ValueError: ignored

In [ ]:
A * 2. # element wise multiplication

array([2, 4, 6])

In [ ]:
l * 2. #repeated concatenation

[1, 2, 3, 'd', 1, 2, 3, 'd']

In [ ]:
l + l. #addition for lists is always concatenation

[1, 2, 3, 'd', 1, 2, 3, 'd']

In [ ]:
l = [1,2,3]. #must iterate to add to list elements
l2 = []
for i in l:
  l2.append(i + 3)
l2

[4, 5, 6]

In [ ]:
#list comprehensions
l2 = [e + 3 for e in l]
l2

[4, 5, 6]

In [ ]:
l**2. #no multiplication for lists, must iterate

TypeError: ignored

In [ ]:
l3 = [e**2 for e in l]
l3

[1, 4, 9]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A). #all functions over the vector

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:
np.sin(A)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
A = np.array([1,2])
B = [e**2 for e in A]

In [ ]:
A.dot(B)

9

In [ ]:
dot = 0
for i in range(len(A)):
  dot += A[i] * B[i]
dot

9

In [ ]:
A * B. #element wise

array([1, 8])

In [ ]:
np.sum(A*B)

9

In [ ]:
(A*B).sum()

9

In [ ]:
np.dot(A,B)

9

In [ ]:
# new operator
A @ B

9

In [ ]:
np.norm(A)

AttributeError: ignored

In [ ]:
Amag = np.sqrt(A @ A)
print(Amag)

2.23606797749979


In [ ]:
np.linalg.norm(A). #norm

2.23606797749979

In [ ]:
# cosine
cos = A @ B / (np.linalg.norm(A) * np.linalg.norm(B))
cos

0.9761870601839528

In [ ]:
angle = np.arccos(cos)
angle

0.21866894587394162